---
- name: Install vsftpd
  apt: name=vsftpd state=present
  sudo: yes
  notify: stop-vsftpd
- name: copy vsftpd config file
  copy: src=vsftpd.conf dest=/etc/vsftpd.conf
  sudo: yes
  notify: start-vsftpd
- name: start tomcat
  service: name=tomcat7 state=started
- name: Start tomcat
  service: name=tomcat7 state=started
- name: wait for tomcat to start
  wait_for: path=/var/lib/tomcat7/logs/catalina.out search_regex="Server Started"
- name: Run custom sql file
  shell: mysql dlo < data.sql
