---
- name: Install mysql
  apt: name={{ item }} state=present
  with_items:
    - python-mysqldb
    - mysql-server
  notify: Start mysql server
- name: Mysql | Set root password
  shell: debconf-set-selections << 'mysql-server mysql-server/root_password password root'
- name: Mysql | Set root repassword
  shell: debconf-set-selections << 'mysql-server mysql-server/root_password_again password root'
- name: update mysql root password for all root accounts
  mysql_user: name=root host=localhost password={{ mysql_root_password }} priv=*.*:ALL,GRANT
- name: copy .my.cnf file with root password credentials
  template: src=.my.cnf dest=/root/.my.cnf owner=root mode=0600
- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ root_db_password }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1

- name: Create the app user for dlo 
  mysql_user: name=app password=password priv=*.*:ALL,GRANT state=present

- name: Create the database
  mysql_db: name=dlo state=present